export default {
    "data": [
        {
            "author": "scrappykitty",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Exactly. I have a Republican co-worker who thinks John McCain and Lindsey Graham are left of Center and, of course, he thinks Obama is Stalin. In reality, Obama could be classified as a moderate democrat on the spectrum. The right in America is far more tribal than the left. ",
            "created_utc": 1511536988,
            "id": "dqa0u1o",
            "link_id": "t3_7f60uz",
            "parent_id": "t1_dq9z9yl",
            "permalink": "/r/reactiongifs/comments/7f60uz/mrw_my_super_far_left_sisters_get_into_an/dqa0u1o/",
            "retrieved_on": 1511536989,
            "score": 1,
            "stickied": false,
            "subreddit": "reactiongifs",
            "subreddit_id": "t5_2t5y3"
        },
        {
            "author": "Renathras",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I used to hold this view...until Obamacare.  Then I saw EVERY Democrat in the Senate vote for it, regardless of their character.  And I saw EVERY vote they needed vote for it in the House (the Democrats who voted against it only did so after they had seen that it had the numbers it needed to pass).\n\nIt was then that I realized that abominations and affronts to personal liberty (something intensely important to me) would be passed by people I had previously thought were moral - I had voted for the Democrat House representative in my district in Waco, Tx the previous election because I thought he was a decent guy, but he was one of the Democrats who waited until it had the votes to pass before casting his vote against it.  He lost the following election in a landslide.\n\nObamacare/ACA is the reason I haven't voted for Democrats in 8 years.  I still vote for other parties besides Republican (chiefly the Libertarian party), but not Democrats.  And I can no longer say that morals will trump policy - a position I held before the Democrats rammed Obamacare down my throat (particularly, the Individual Mandate - if the whole rest of the ACA was still law, but the IM was repealed, I would see it as a poor piece of legislation, but I wouldn't find it chaffing to my very notions of personal liberty).\n\nRegardless of what you think of my views or assessment, I'm more saying that this position sounds noble, until you see something egregious (to you) happen because of it (for example, suppose you voted for a moral Republican over an immoral Democrat...and then that Republican was a deciding vote that allowed abortion to be outlawed, illegal \"dreamers\" to be deported, etc).  It's easy to hold a moral high ground in a thought experiment.\n\nAdditionally, it would be nice if we could get 100 Senators who will listen and talk...but I think we all know that's not happening.  If there was even a chance of that, it would start with moderate Dems and Reps being able to agree on things, but even that's not happening - the reason the Republicans are having to bow to the wishes of the far right members of their caucus is because NO \"moderate\" Democrats will vote with them on essentially ANY issue, even when they offer generous compromises.  The only exceptions are \"must pass\" legislation, like Defense authorization, and even then the \"moderate\" Democrats aren't voting for it, they're just not filibustering it.\n\nSo given that we aren't getting a bunch of people interested in compromise, I think that's where the morality vs ideology argument breaks down:\n\nYou're either participating in a Representative Democracy to get a candidate that will represent your views, or you're abdicating your right to ideological representation by voting for the candidate that doesn't agree with your views.  Unfortunately, there are essentially no moderates that will cross party lines anymore.\n\nThere are a few (essentially all Republicans) like McCain out there, but that's really it.  Manchin or Sanders on issues like gun rights, maybe?  Outside of those specific cases, I honestly can't think of any.",
            "created_utc": 1511529269,
            "id": "dq9wemo",
            "link_id": "t3_7eu2w4",
            "parent_id": "t1_dq7k8td",
            "permalink": "/r/PoliticalDiscussion/comments/7eu2w4/how_should_voters_respond_to_argumentsallegations/dq9wemo/",
            "retrieved_on": 1511529270,
            "score": 1,
            "stickied": false,
            "subreddit": "PoliticalDiscussion",
            "subreddit_id": "t5_2sfmf"
        },
        {
            "author": "Renathras",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Realistically speaking, you have to ask yourself the purpose of Representative Democracy.\n\nIf it is to elect moral people, than we have a horrible system for that.  If the goal is to elect moral people, they we need elections that do not have parties or platforms, do not have ideology battles or policies mentioned or debated.  Only the morals of the person.\n\n...additionally, we would have to have a uniform idea of what is immoral - remember that Democrats have spent the last 20 years arguing for relativistic morality; that, for example, a Christian cannot tell a gay person that being gay is a sin and refuse to bake them a gay wedding cake.  So it's very strange to now see that same side (Democrats) arguing that immoral behavior is a problem, since their efforts over the last 20 years plus has been that morals aren't an issue and what people do outside of the public sphere is between them (that is, Democrats were previously libertarian on the issue...they no longer are).\n\nThe third problem - and where we are now - is that the goal of Representative Democracy is that people have representatives that go and vote on their behalf.  Due to us being so polarized and both parties having moved so far apart (Democrats to the left, Republicans to the right), the middle ground is scarce.  Republicans couldn't propose a moderate bill right now in Congress that the far right would refuse to vote for but that moderate Democrats would cross the isle to join in on, other than perhaps a Defense appropriation bill (\"must pass\" legislation).  Even if the Republicans proposed a \"moderate\" ACA repeal or tax cut bill, \"moderate\" Democrats aren't going to vote for it.\n\nAnd the same happened when their situations were reversed.\n\nEffectively, there is no center anymore, so there's no room for voters to vote for the other party's candidate except in the purplest of purple swingiest of swing states.\n\nAnd then you get the zero tolerance issues - for example, the Democrat leadership has more or less determined (in line with the women's rights feminist SJW crowd) that there will be no support from the national party for pro-life Democrat candidates.\n\n...and this is why they're likely going to lose Alabama!\n\nIf Doug Jones had thought from the start of the race he had a shot, or the Democrats thought back in the primary they had a shot, they could have put forward a moderate candidate on the social issues.  Then, when Moore's popularity tanked in light of all the allegations, Jones could have credibly swooped in to grab the votes of more moderate Republicans.\n\nThe problem is, because he's been so outspokenly pro-choice (up to the point of birth - he's tried walking it back this last week, but the damage has been done), the voters can be convinced that the have a choice between an accused (not proven) pedophile or an admitted proponent of baby mass murderer.  Which is an easy enough choice for the Alabama population that is Republican +20 or something advantage.\n\n.\n\nSo that's the rub:\n\nAre we a Representative Democracy or a Moral Republic?\n\nDemocrats have spent decades convincing us that we are the former, and now are trying to convince us that we're the latter because they think it will benefit them in the short term and they can flip the script later if it advantages them to do so.\n\nIt's no surprise that Republicans are reacting the way they are, especially since their views (especially on social issues) have been the most harried and challenged over the last decade.  They're now the proponents for Representative Democracy as a desperate hope to prevent all the ground they've been losing in the culture wars.\n\n.\n\nUltimately, I believe in Representative Democracy.\n\nI feel like accusations like these should come out and be vetted in the Primaries, that way in the General, people still have a choice between picking moral candidates that ALSO represent their ideological views.  It's also why I find accusations that come out in the General election (especially late in the General) to be suspect - the goal at that point is to flip the seat, not to weed out bad candidates.\n\nI also have issue with this assertion that a preponderance of accusation is a preponderance of evidence, especially when we're decades removed from the events (even the Frankin events were more than half a decade ago, at least the ones I'm aware of), and when they are past the statute of limitations so that the accused will never get a day in court to prove their innocence, and/or where people cast aside the VERY NECESSARY \"innocent until proven guilty\" axiom.\n\nIn light of all of that, I believe that voting for ideology makes the most sense.  Until our politics change, the way we have elections changes, or the conversation changes seriously - not just Democrats and SJWs trying to spike the conversation to further their own interests but EVERYONE coming together to discuss what we collectively think is and isn't off limits, and doing so not during elections but before elections so we can set ground rules (not change the rules of the game in the 4th quarter) - until that happens, voting ideology is what makes the most sense.\n\n...and it's what you can count on the \"other side\" to do, that's for certain.  If Democrats are willing to continue supporting the likes of Frankin, then it's obvious their gripes are to gain political power, not a genuine concern for the issue (as many on the left who HAVE opposed Frankin have noted.)",
            "created_utc": 1511527243,
            "id": "dq9vitq",
            "link_id": "t3_7eu2w4",
            "parent_id": "t3_7eu2w4",
            "permalink": "/r/PoliticalDiscussion/comments/7eu2w4/how_should_voters_respond_to_argumentsallegations/dq9vitq/",
            "retrieved_on": 1511527244,
            "score": 1,
            "stickied": false,
            "subreddit": "PoliticalDiscussion",
            "subreddit_id": "t5_2sfmf"
        },
        {
            "author": "feoohh2o",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "The default subs (like r/politics) tend to be more liberal leaning, but there are plenty of other, more conservative leaning subs, e.g r/conservative, /r/Republican, /r/tuesday (which I moderate), etc...",
            "created_utc": 1511521953,
            "id": "dq9tlsu",
            "link_id": "t3_7f1g58",
            "parent_id": "t3_7f1g58",
            "permalink": "/r/TheoryOfReddit/comments/7f1g58/why_is_reddit_so_liberal/dq9tlsu/",
            "retrieved_on": 1511521954,
            "score": 1,
            "stickied": false,
            "subreddit": "TheoryOfReddit",
            "subreddit_id": "t5_2rtff"
        },
        {
            "author": "BDZM",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "The next Republican president is very likely to be much more moderate and even-handed, if it makes you feel better. The RNC is going to pull out all the stops to get their candidate in front, it will make Clinton/Schultz manipulation look like child's play. They don't want another Trump. The entire party despises him.",
            "created_utc": 1511519675,
            "id": "dq9su9u",
            "link_id": "t3_7f14hu",
            "parent_id": "t1_dq966wf",
            "permalink": "/r/politics/comments/7f14hu/gop_insider_bruce_bartlett_the_republican_party/dq9su9u/",
            "retrieved_on": 1511519678,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "OhhWhyMe",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "The second they impeach him without wide support from republicans (he has 70-80 % approval with Rs last time I checked) is the second that the Republican party would be fractured in two.  The moderate republicans would support the impeachers and the Trumpsters would throw a rage fit and the Rs would lose their votes in all future elections.  This is about appeasing the 30% of idiot voters in the country to keep voting R no matter what, it has nothing to do with Trump.  Literally party over country.",
            "created_utc": 1511517373,
            "id": "dq9s1yf",
            "link_id": "t3_7f4app",
            "parent_id": "t1_dq9jk5z",
            "permalink": "/r/politics/comments/7f4app/congress_braces_for_russia_sanctions_faceoff_with/dq9s1yf/",
            "retrieved_on": 1511517374,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "KicksButtson",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Turns out that pandering to the far left won't win over the moderate voters, who knew?... Well, just about everyone who worked in politics before the end of the Cold War knew that.\n\nThe far left is going to vote Democrat because they know their extreme left candidates don't have a chance of winning, so even if the Democratic candidate is only left of center they can be sure they've got the leftist fringe vote in the bag. One thing is for certain, they're definitely not going to vote for the Republican candidate. Knowing that, it's pretty obvious that you don't need to pander to a political demographic who is already guaranteed to vote for you, especially when pandering to that far left demographic annoys the moderates whose votes you actually need.\n\nNeither side can secure an election without also securing the moderate swing voters who make up a majority of the voting public. But both sides alienate moderate voters by pandering to their far right and left demographics to secure their party nomination in the first place, and once the pandering train has left the station it's hard to change course. The candidate and his campaign advisors see their bandwagon gaining momentum and they're not about to switch tactics mid race.\n\nIn the end moderate voters were split down the middle because neither side seemed appealing. I think Trump only won because he was addressing issues that both sides had been ignoring for a long time, and that at least showed some sign that he could change something.",
            "created_utc": 1511507914,
            "id": "dq9oe5m",
            "link_id": "t3_7f1c7n",
            "parent_id": "t1_dq9o5aw",
            "permalink": "/r/gaming/comments/7f1c7n/wtf_fallout_you_always_surprise_me/dq9oe5m/",
            "retrieved_on": 1511507916,
            "score": 1,
            "stickied": false,
            "subreddit": "gaming",
            "subreddit_id": "t5_2qh03"
        },
        {
            "author": "THVAQLJZawkw8iCKEZAE",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "ADDRESSING over 2,000 conservative lawyers and friends at a banquet in central Washington, DC, last week, Neil Gorsuch was in jocular form. \u201cIf you\u2019re going to have a meeting of a secret organisation, maybe don\u2019t have it in the middle of Union Station!\u201d quipped the newest Supreme Court judge. This was disingenuous. The reason many worry about the Federalist Society, the legal organisation whose annual bunfight Justice Gorsuch was addressing, is not because it is shadowy, but because its influence is vast, brazen and part of a wider politicising of the last branch of American democracy to succumb to partisanship. His speech suggested those worries are if anything underplayed.\n\nTwo things about it were most striking. First, the triumphalist tone Mr Gorsuch, a supposedly impartial steward of the constitution, struck in celebrating the legal philosophy and activism of a group closely linked to the Republican Party. \u201cTonight, I can report, a person can be both a committed originalist and a textualist and be confirmed to the Supreme Court!\u201d he said. \u201cThank you from the bottom of my heart for your support and prayers through that process.\u201d If that was perhaps inappropriate, it was deserved. Founded in the early 1980s, as a riposte to the legal profession\u2019s liberal mainstream, the Federalist Society has had a hand in the past three Republican Supreme Court appointments\u2014starting with its frosty response to George W. Bush\u2019s nomination of Harriet Miers and promotion of Samuel Alito in her place. Yet its role in Mr Gorsuch\u2019s elevation is much greater.\n\nAs the youngest conservative justice, he is the first to have been a beneficiary of its now-ubiquitous legal networks throughout his career. Less ideological ways for conservative judges to advance\u2014including senatorial favour or working for the Republican Party\u2014have meanwhile fizzled. When Donald Trump, in need of conservative credentials last year, demanded a list of potential Supreme Court nominees, it was natural he would turn to the \u201cFederalist people\u201d for their suggestions, which included Mr Gorsuch. Having ridden that promise to victory, Mr Trump has since sidelined the American Bar Association, which traditionally vets judicial nominees, and outsourced the process to the society\u2014or rather insourced it, the White House counsel, Donald McGahn, noted at its annual shindig, because he is also a member.\n\nThe second striking thing about Mr Gorsuch\u2019s speech was his boldness in signalling a legal agenda\u2014curtailing the federal bureaucracy\u2019s power to interpret statutes\u2014he means to pursue. This implied two sorts of departure from Antonin Scalia, the originalist he succeeded. Scalia deferred to both the executive and a tradition whereby justices reveal their thinking more in legal opinions than after-dinner speeches. Mr Gorsuch\u2019s remarks\u2014which even an approving legal scholar in the audience considered to be \u201ctiptoeing the sideline\u201d of propriety\u2014augur a more activist approach.\nThe prospect of more ideological and active conservative judges is not intrinsically bad. The federal courts look stronger for including a range of legal philosophies. The problem is that conservatives are not striving for balance, but conquest. That is the logic of Mr Gorsuch\u2019s divisive rhetoric. It is also Mr McGahn\u2019s plan, encouraged by a president who cares not a whit for legal philosophy, but who has found his promise to appoint conservative judges to be uniquely effective and achievable.\n\nWith three liberal or moderate Supreme Court justices, Stephen Breyer, Ruth Bader Ginsburg and Anthony Kennedy, in or approaching their 80s, Mr Trump may well increase the court\u2019s conservative majority. The lower federal courts are even more vulnerable to an ideological makeover. Because Republican senators refused to approve many of Barack Obama\u2019s nominees, Mr Trump inherited many empty seats on the benches, which the Democrats\u2019 decision to scrap the use of the filibuster in judicial appointments has made easy to fill. His administration has so far nominated 59 judges, three times as many as Mr Obama at the same point in his tenure, and with almost half of the 150 appellate judges of retirement age, it expects to nominate many more. Some ideologues are still unsatisfied; Steven Calabresi, a Federalist Society co-founder, suggests packing the federal courts with at least 260 new judgeships. Mr Trump\u2019s recent boast that, \u201cThere has never been anything like what we\u2019ve been able to do together with judges,\u201d could prove to be unusually accurate.\n\nIt is hard to exaggerate how significant, divisive and fundamentally antithetical to the Federalist Society\u2019s original purpose this project is. It represents an assault on the courts\u2019 already-tested consensual traditions, which the next Democratic administration would naturally emulate, thereby dividing the courts even more nakedly along partisan lines and making judicial appointments even more politicised than they already are. The society\u2019s founding mission was to defend the separation of powers: its extremism threatens to erode whatever open ground remains between the judiciary and elected branches. Bruce Ackerman, a legal scholar, predicts the federal courts are heading for a period of \u201chyper-politicisation\u201d not seen since the 1930s, when Franklin Roosevelt went to war with the Supreme Court over its hostility to the New Deal.\n\nThis is not only bad for the courts. The irony of the Federalist Society\u2019s pact with Mr Trump is that a movement dedicated to defending the constitution has enabled a president whose conflicts of interest, disregard for due process and disparagement of independent agencies and actors\u2014including \u201cso-called judges\u201d\u2014represent a grave constitutional threat. Conservative lawyers know this. Many have told Lexington of their unease with almost everything Mr Trump is doing outside judicial appointments. Yet instead of acting on principle, they keep raising the price of their support, and Mr Trump, who knows a good deal when he sees one, keeps paying the bill.",
            "created_utc": 1511507655,
            "id": "dq9oa3v",
            "link_id": "t3_7f11qk",
            "parent_id": "t3_7f11qk",
            "permalink": "/r/politics/comments/7f11qk/conservative_lawyers_are_among_the_presidents/dq9oa3v/",
            "retrieved_on": 1511507656,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "AtlaStar",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Personally I don't know...Thing is I personally see libertarianism as more of an ideology than a structured party similar to anti-fascism...and because of that I see that the Johnson style of libertarian is basically an analogue to a democrat that is extremely progressive in regards to social issues, but closer to the conservative or moderate republican (not current GOP, but probably the early or pre-Reagan era GOP) in regards to government spending and corporations as a whole.",
            "created_utc": 1511504369,
            "id": "dq9mptl",
            "link_id": "t3_7f47yo",
            "parent_id": "t1_dq9m5a0",
            "permalink": "/r/politics/comments/7f47yo/trump_golfs_tweets_on_thanksgiving_eve_while/dq9mptl/",
            "retrieved_on": 1511504370,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "roudyrod",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I know a guy who is a staffer for a federal rep.  They truly do not give a fuck.  They just keep hitting delete till the mailbox is empty.  Calling makes a bigger impact but the majority of the people calling are the political extremist who wanna know why the rep isn\u2019t spearheading the effort to lock up Hillary or investigate Obama.\n\nThe reality of it is that the vast majority of their time is spent fundraising and they can still pass publicity unpopular legislation because they can afford to run ads about how their opponant loves abortion, Satan and is BFFs with George Soros and Nancy Pelosi.  This friend of mine works for a moderate republican who is WAY more afraid of getting primaried by a guns n\u2019 Jesus Roy Moore type than he is losing to a Democrat in the general.\n\nBasically what I\u2019m saying is the unless you can afford to go to DC and stalk the congressman for a few weeks or go to the next 50K a plate fundraiser, your voice means nothing to them.\n\nI\u2019m not trying to discourage anyone from calling, just explaining how it plays out in real life.\n\n",
            "created_utc": 1511497798,
            "id": "dq9j2p1",
            "link_id": "t3_7ek1r0",
            "parent_id": "t1_dq5qu17",
            "permalink": "/r/texas/comments/7ek1r0/ted_cruz_applauds_chairman_pai_for_ending_net/dq9j2p1/",
            "retrieved_on": 1511497800,
            "score": 1,
            "stickied": false,
            "subreddit": "texas",
            "subreddit_id": "t5_2qho4"
        },
        {
            "author": "therealrico",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Our recent republican governors are pretty moderate.",
            "created_utc": 1511494113,
            "id": "dq9goxb",
            "link_id": "t3_7ezun1",
            "parent_id": "t1_dq8id53",
            "permalink": "/r/vermont/comments/7ezun1/why_is_vermont_so_liberal/dq9goxb/",
            "retrieved_on": 1511494114,
            "score": 1,
            "stickied": false,
            "subreddit": "vermont",
            "subreddit_id": "t5_2qqdd"
        },
        {
            "author": "choclatechip45",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Isn't he exploring a race for congress to run against Himes? To bad he is a fake moderate republican.",
            "created_utc": 1511492246,
            "id": "dq9fgqz",
            "link_id": "t3_7f3uki",
            "parent_id": "t3_7f3uki",
            "permalink": "/r/Connecticut/comments/7f3uki/no_response_from_r_senator_tony_hwang_on_net/dq9fgqz/",
            "retrieved_on": 1511492248,
            "score": 1,
            "stickied": false,
            "subreddit": "Connecticut",
            "subreddit_id": "t5_2qji0"
        },
        {
            "author": "With-a-Cactus",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "In my family I'm a bleeding heart liberal, but to my liberal friends I'm a moderate republican. If people are never exposed to views besides their own, they will always find the world extreme.",
            "created_utc": 1511485350,
            "id": "dq9ax9f",
            "link_id": "t3_7f1fh8",
            "parent_id": "t1_dq956bg",
            "permalink": "/r/AdviceAnimals/comments/7f1fh8/net_neutrality_shouldnt_be_a_partisan_issue/dq9ax9f/",
            "retrieved_on": 1511485351,
            "score": 1,
            "stickied": false,
            "subreddit": "AdviceAnimals",
            "subreddit_id": "t5_2s7tt"
        },
        {
            "author": "lokthurala10",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I'm pretty liberal by American standards, but liberal and conservative don't really mean anything as everyone interprets it their own way. I grew up in a town that was 95% white, 95% Republican. Everyone says they're conservative or moderate but often believe in very liberal ideas, both socially and economically. ",
            "created_utc": 1511482838,
            "id": "dq99a27",
            "link_id": "t3_7f0yjs",
            "parent_id": "t3_7f0yjs",
            "permalink": "/r/AskAnAmerican/comments/7f0yjs/are_you_more_conservative_or_liberal/dq99a27/",
            "retrieved_on": 1511482843,
            "score": 1,
            "stickied": false,
            "subreddit": "AskAnAmerican",
            "subreddit_id": "t5_2uah7"
        },
        {
            "author": "De1CawlidgeHawkey",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I used to moderate /r/politics probably ~4ish years ago (not on this account).  \n    \nThe moderation team actually wasn't that liberal. In fact, we got frustrated because the userbase was extremely left leaning (this is back when we were a default, so we tried to make it unbiased l or r) and would call ANYTHING that was conservative out as being posted by a \"shill\". Constant reports complaining about republican shills. Don't get me started about how when we removed something that broke a clearly stated rule how we got witch-hunted for being proponents of censorship. Oh man, it got so old so fast for all of us.\n  \nEventually, when you're a *volunteer* moderation team, you wonder why the fuck you're dealing with that everyday. So you drop it -- and then people who can handle it (people who are also biased) come on the team and last a long time because the biases don't bother them.  \n  \n \n I'm afraid that's just the natural cycle when you have users who are so toxic; and you can't really do anything about it (because you're 100% correct, this was back when mods were huge on free speech so we were EXTREMELY hesitant to remove any comments that didn't violate an explicitly stated rule.)  \n  \n  \nSo OP, my best guess is that there are still a lot of republicans/conservatives, but why would you ever comment when you know you're gonna log back on to 50 red messages chewing you out? I mean, I still do it because I don't give a fuck -- but I know for most people it's not worth the hassle.",
            "created_utc": 1511482656,
            "id": "dq995kz",
            "link_id": "t3_7f1g58",
            "parent_id": "t1_dq94ltv",
            "permalink": "/r/TheoryOfReddit/comments/7f1g58/why_is_reddit_so_liberal/dq995kz/",
            "retrieved_on": 1511482657,
            "score": 1,
            "stickied": false,
            "subreddit": "TheoryOfReddit",
            "subreddit_id": "t5_2rtff"
        },
        {
            "author": "AirRaidJade",
            "author_flair_css_class": "ohio text",
            "author_flair_text": "Ohio",
            "body": "I'm a left-leaning centrist. I almost always vote for Democrats, but I consider myself an independent and don't necessarily support *all* Democrats. I generally dislike Republican ideals, although I'm alright with a few of the more moderate ones. Regardless of whether you're liberal or conservative, the more moderate you are, the better we'll get along.",
            "created_utc": 1511476841,
            "id": "dq951mp",
            "link_id": "t3_7f0yjs",
            "parent_id": "t3_7f0yjs",
            "permalink": "/r/AskAnAmerican/comments/7f0yjs/are_you_more_conservative_or_liberal/dq951mp/",
            "retrieved_on": 1511476843,
            "score": 1,
            "stickied": false,
            "subreddit": "AskAnAmerican",
            "subreddit_id": "t5_2uah7"
        },
        {
            "author": "Ofbearsandmen",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Same. I don't understand how moderate Republicans have turned into this. I mean, there have to be people who are conservative for what I'd call intelligent reasons. But anyone who calls themselves fiscally responsible can't back this bill. It's an insane one. It's not conservative, it's revolutionary, as in backwards revolutionary. The only explanation is that after 40 or so years of the GOP focusing only on single-issue voters, the part of their electorate who voted them for economic and fiscal policy reasons have died, stopped voting or turned Democrat. After all 40 years is a long time, almost two generations. It's entirely possible that reasonable Republican voters have almost disappeared.",
            "created_utc": 1511476412,
            "id": "dq94qfe",
            "link_id": "t3_7eysjj",
            "parent_id": "t1_dq93rmt",
            "permalink": "/r/esist/comments/7eysjj/37_of_38_economists_said_the_gop_tax_plans_would/dq94qfe/",
            "retrieved_on": 1511476412,
            "score": 1,
            "stickied": false,
            "subreddit": "esist",
            "subreddit_id": "t5_3irqb"
        },
        {
            "author": "Dan_Gleeballz",
            "author_flair_css_class": "newhampshire-flag",
            "author_flair_text": "New Hampshire",
            "body": "The best thing that could happen to the United States is for the Republican Party to go away and be replaced by a more moderate, more pragmatic Conservative party.  America needs a loyal conservative opposition, but not a batshit insane one.",
            "created_utc": 1511467597,
            "id": "dq8xzpy",
            "link_id": "t3_7f14hu",
            "parent_id": "t1_dq8qjyf",
            "permalink": "/r/politics/comments/7f14hu/gop_insider_bruce_bartlett_the_republican_party/dq8xzpy/",
            "retrieved_on": 1511467599,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "indianawalsh",
            "author_flair_css_class": "donation stevens image",
            "author_flair_text": "Thaddeus Stevens",
            "body": "name \ud83d\udcdb 1 \ud83c\udf84 democrat \ud83d\udc34 economic policy \ud83d\udca1 that \ud83d\ude10 this \ud83d\udc48 sub \ud83c\udf2f supports. Almost \ud83d\udcb8 every \ud83d\udc4f thread i \ud83d\udc41 \ud83d\udc40 supports only \ud83d\udd66 republican \ud83d\udc6f i \ud83d\udc41 do \ud83d\udc4c not \ud83d\udeab \ud83d\udc40 \ud83c\udd70 \ud83c\udffb single \ud83c\udffb thread supporting any \ud83d\udca6 democratic \ud83d\udc34 policies &amp; whenever \ud83c\udfea i \ud83d\udc41 bring \ud83d\udeb6 \ud83c\udd99 liberal \ud83d\udc68 policies u \ud83d\udc48 guys \ud83d\udc68 denounce. \ud83d\ude45 \ud83d\ude45 guys \ud83d\udc68 r \ud83d\ude02 not \ud83d\udeab center \ud83d\udc48. Ur \ud83d\udc56 goal \ud83d\udc95 is \ud83d\udca6 2 \ud83d\udd5d ensure the \ud83d\udc4f minimum standard of \ud83d\udca6 living \ud83d\udc19 while \ud83d\udd57 being \ud83d\ude11 hyper focused on \ud83d\udd1b supporting economic efficency with \ud83d\udc4f little \ud83d\udc4c \ud83d\udcad 2 \ud83d\udd5d that \ud83d\ude10 is \ud83d\udca6 not \ud83d\udeab center \ud83d\udc48 that \ud83d\ude10 is \ud83d\udca6 center \u27a1. \ud83d\udca5 Center right=vigirously support \ud83d\udc96 economic efficency while \ud83d\udd57 throwing \ud83c\udd70 \ud83c\udffb few \ud83d\udc47 \ud83c\udf5e crumbs \ud83d\udca9 at \ud83c\udf46 the \ud83d\udc4f poor. \ud83d\udcb8 Center left=support maximum \ud83d\udca6 standard of \ud83d\udca6 living \ud83d\udc19 in \ud83d\udc4f \ud83c\udd70 \ud83c\udffb fically efficent, responsible \ud83d\udc4d &amp; pragmatic manner. This \ud83d\udc48 sub \ud83c\udf2f is \ud83d\udca6 focused on \ud83d\udd1b economic effiency i \ud83d\udc41 have \ud83d\udc4f literally \ud83d\udc4b \ud83d\udc40 threads \ud83d\udcac about \ud83d\udca6 whether \ud83c\udf29 welfare 4 \ud83d\udca6 \ud83c\udf20ving ppl \ud83d\udc65 is \ud83d\udca6 in \ud83d\udc4f of \ud83d\udca6 itself \ud83d\ude9d economically effiecent &amp; is \ud83d\udca6 better \ud83d\udc4d 2 \ud83d\udd5d just \ud83d\udc4f \u270b poor \ud83d\udcb8 coal \ud83c\udf11 miners welfare checks \ud83d\udc4c over \ud83d\udc4f retraining them \ud83d\udca6 cuz \ud83d\udc4f it \ud83d\udcaf would \ud83d\udc6a economically more \ud83c\udf57 efficent. Progress \ud83d\udc80 at \ud83c\udf46 all \ud83d\udcaf expenses is \ud83d\udca6 what \ud83d\ude26 this \ud83d\udc48 sub \ud83c\udf2f is. \ud83d\udca6 Also \ud83d\udc68 this \ud83d\udc48 sub \ud83c\udf2f claims 2 \ud83d\udd5d b \ud83d\ude0e socially liberal, \ud83d\udc68 however, \ud83d\udd90 it \ud83d\udcaf is \ud83d\udca6 not. \ud83d\udeab U \ud83d\udc48 cannot \ud83d\udeab b \ud83d\ude0e socially liberal \ud83d\udc68 w/o being \ud83d\ude11 somewhat \ud83d\udca9 economically \ud83d\udc48 wing. Y? \ud83d\udde3 social \ud83d\udcd6 liberalism seeks \ud83d\udc40 2 \ud83d\udd5d solve social \ud83d\udcd6 ills while \ud83d\udd57 this \ud83d\udc48 sub \ud83c\udf2f seems \ud83d\udc40 2 \ud83d\udd5d not \ud83d\udeab give \ud83d\udc49 \ud83c\udd70 \ud83c\udffb fuck \ud83c\udf46 about \ud83d\udca6 them \ud83d\udca6 since \ud83d\udc68 2 \ud83d\udd5d do \ud83d\udc4c so \ud83d\udcaf u \ud83d\udc48 need \ud83d\udc49 2 \ud83d\udd5d spend \ud83d\udcb0 \ud83d\udcb0 on \ud83d\udd1b poor \ud83d\udcb8 ppl \ud83d\udc65 when \ud83c\udf51 litterally ur \ud83d\udc56 policies argue 4 \ud83d\udca6 the \ud83d\udc4f opposite ex. rampant \ud83d\udc7f of \ud83d\udca6 unions which \ud83d\udc4f literally \ud83d\udc4b r \ud83d\ude02 the \ud83d\udc4f reason \ud83c\udf1f y \ud83d\udde3 blue \ud83d\udc99 states \ud83d\udc4c have \ud83d\udc4f \ud83c\udd70 \ud83c\udffb much \ud83d\udd25 lower rate of \ud83d\udca6 industrial accident \ud83d\udc80s than \ud83d\udc49 red \ud83d\udcdb states \ud83d\udc4c (you \ud83d\udc48 cannot \ud83d\udeab seperate \ud83d\udeb4 1 \ud83c\udf84 from \ud83d\udc49 the \ud83d\udc4f other). \ud83d\udc6a In \ud83d\udc4f reality \ud83d\ude31 ppl \ud83d\udc65 here \ud83d\udc4f r \ud83d\ude02 social \ud83d\udcd6 libertarians. \ud83d\udc74 In \ud83d\udc4f that \ud83d\ude10 they \ud83d\udc65 claim \ud83d\udc4f 2 \ud83d\udd5d b \ud83d\ude0e all \ud83d\udcaf progressive \ud83d\uddfd &amp; oh \ud83d\ude40 i \ud83d\udc41 accussed u \ud83d\udc48 of \ud83d\udca6 ableism but \ud83c\udf51 when \ud83c\udf51 push \ud83c\udffd comes \ud83d\udca6 2 \ud83d\udd5d shove \ud83d\ude20 ur \ud83d\udc56 not \ud83d\udeab \ud83c\udd70 \ud83c\udffb true \ud83d\udcaf social \ud83d\udcd6 justice \ud83d\udc6e warrior. U \ud83d\udc48 cannot \ud83d\udeab seperate \ud83d\udeb4 economic issues \ud83d\udcdd &amp; social \ud83d\udcd6 issues \ud83d\udcdd \ud83d\udc4d this \ud83d\udc48 sub \ud83c\udf2f tries \ud83d\ude2b 2 \ud83d\udd5d do. \ud83d\udc4c Overall i \ud83d\udc41 do \ud83d\udc4c tend 2 \ud83d\udd5d support \ud83d\udc96 \ud83c\udd70 \ud83c\udffb lot \ud83c\udf51 of \ud83d\udca6 the \ud83d\udc4f economic policies except \ud83d\ude2e on \ud83d\udd1b certain \ud83d\udd11 issues \ud83d\udcdd ex. unions, labor \ud83d\udc68 laws, \ud83d\udd8e healthcare, \ud83c\udfe5 net \ud83c\udfc0 neutrality, free \ud83d\udc9c community \ud83d\udc69 college. \ud83c\udfeb Overall while \ud83d\udd57 its \ud83d\ude45 fine \ud83d\udc4c 2 \ud83d\udd5d have \ud83d\udc4f the \ud83d\udc4f policy \ud83d\udca1 positions \ud83d\udcaf u \ud83d\udc48 guys \ud83d\udc68 have \ud83d\udc4f 2 \ud83d\udd5d claim \ud83d\udc4f 2 \ud83d\udd5d b \ud83d\ude0e \ud83c\udd70 \ud83c\udffb democrat \ud83d\udc34 pisses. \ud83c\udf46 Most \ud83d\udcaf of \ud83d\udca6 ur \ud83d\udc56 economic positions \ud83d\udcaf r \ud83d\ude02 often opposite of \ud83d\udca6 democrat \ud83d\udc34 &amp; more \ud83c\udf57 often than \ud83d\udc49 not \ud83d\udeab u \ud83d\udc48 support \ud83d\udc96 the \ud83d\udc4f republicans on \ud83d\udd1b almost \ud83d\udcb8 every \ud83d\udc4f issues \ud83d\udcdd with \ud83d\udc4f maybe \ud83d\udc4f \ud83c\udd70 \ud83c\udffb few \ud83d\udc47 \ud83c\udf5ecrumbs thrown at \ud83c\udf46 the \ud83d\udc4f poor \ud83d\udcb8 so \ud83d\udcaf u \ud83d\udc48 can \ud83d\udca6 feel \ud83d\ude01 \ud83c\udd70 \ud83c\udffb little \ud83d\udc4c more \ud83c\udf57 socially liberal \ud83d\udc68 when \ud83c\udf51 ur \ud83d\udc56 not. \ud83d\udeab Political \ud83c\udfdb positions \ud83d\udcaf center \ud83d\udc49 (ex. Nelson rockefeller)-neoliberal-you guys \ud83d\udc68 r \ud83d\ude02 really \ud83d\ude0d rockefeller \ud83d\udee2 republicans (republican \ud83d\udc6f lite), \ud83d\udc4c ex. Manchin centrist (ex. Bill clinton)-at \ud83d\udc96 bill clinton \ud83d\udc78 was \ud83d\udc4f center \ud83d\udc48 but \ud83c\udf51 had \ud83d\udc8b 2 \ud83d\udd5d b \ud83d\ude0e more \ud83c\udf57 fiscally conservative since \ud83d\udc68 \ud83c\uddf8 was \ud83d\udc4f very \ud83d\udc4c fiscally conservative at \ud83c\udf46 the \ud83d\udc4f \u231a &amp; congress was \ud83d\udc4f majority republican \ud83d\udc6f center \ud83d\udc48 (ex. Obama, \ud83d\udc66 hillary \ud83d\udc75 clinton \ud83d\udc78 etc. )-actual social \ud83d\udcd6 liberals-fiscally center-left-these ppl \ud83d\udc65 have \ud83d\udc4f \ud83d\udc48 wing \ud83d\udcadls but \ud83c\udf51 r \ud83d\ude02 pragmatic pro \ud83d\ude0d market approach \ud83d\ude1c in \ud83d\udc4f achieving them. \ud83d\udca6 they \ud83d\udc65 support \ud83d\udc96 creating \ud83d\udd1c maximum \ud83d\udca6 level \ud83d\udcaf of \ud83d\udca6 living \ud83d\udc19 standard 4 \ud83d\udca6 most \ud83d\udcaf ppl \ud83d\udc65 but \ud83c\udf51 take \ud83d\udc4a pragmatic approach \ud83d\ude1c while \ud83d\udd57 seeking maintain \ud83d\udcaa economy. Obama \ud83d\udc66 appearred 2 \ud83d\udd5d b \ud83d\ude0e \ud83c\udd70 \ud83c\udffb centrist cuz \ud83d\udc4f republicans \u26d4ed his \ud83d\udca6 more \ud83c\udf57 \ud83d\udc48 wing policy \ud83d\udca1 proposals. \ud83d\udc48 (ex. Bernie \ud83d\udc74 sanders, \ud83d\udc74 jeremy corbyn)-have same \ud83d\ude29 goals as \ud83c\udf51 center \u2b05 but \ud83c\udf51 take \ud83d\udc4a less pragmatic, more \ud83c\udf57 government \ud83d\udca9 oriented &amp; tend 2 \ud83d\udd5d demonize anybody \ud83d\udc68 who \ud83d\ude02 is \ud83d\udca6 \u2b05 wing. Btw \ud83d\ude1b did \ud83d\udc4f u \ud83d\udc48 know? \ud83d\udcad bill clinton \ud83d\udc78 increased top \ud83d\udd1d marginal tax rate, corporate tax rate, capital gains \ud83d\ude0e tax rate, housing assistance doesn't \ud83d\ude33 \ud83d\udd0a very \ud83d\udc4c neoliberal. The \ud83d\udc4f fact \ud83d\udcd5 of \ud83d\udca6 the \ud83d\udc4f matter \ud83d\ude45 is \ud83d\udca6 u \ud83d\udc48 can \ud83d\udca6 believe \ud83c\udf08 what \ud83d\ude26 u \ud83d\udc48 want \ud83d\udc4f but \ud83c\udf51 \ud83d\ude4f \u270b calling \ud83d\udcf2 yourself \ud83d\ude0e \ud83c\udd70 \ud83c\udffb democrat \ud83d\udc34 or \ud83d\udc81 \ud83c\udd70 \ud83c\udffb moderate democrat \ud83d\udc34 cuz \ud83d\udc4f ur \ud83d\udc56 not \ud83d\udeab litterally in \ud83d\udc4f this \ud83d\udc48 sub \ud83c\udf2f i \ud83d\udc41 \ud83d\udc40 most \ud83d\udcaf ppl \ud83d\udc65 supporting republican \ud83d\udc6f policies &amp; bashing democratic \ud83d\udc34 policies. How \ud83d\udcaf can \ud83d\udca6 u \ud83d\udc48 call \ud83d\udcf2 yourself \ud83d\ude0e \ud83c\udd70 \ud83c\udffb democratic \ud83d\udc34 when \ud83c\udf51 u \ud83d\udc48 litterally in \ud83d\udc4f this \ud83d\udc48 sub \ud83c\udf2f ppl \ud83d\udc65 supported romney who \ud83d\ude02 wanted \ud83d\ude0d 2 \ud83d\udd5d end \ud83d\udd1a obamacare, reduce environmental regulations, increase \ud83d\udd1b tarrifs on \ud83d\udd1b \ud83c\uddf3. Overall this \ud83d\udc48 sub \ud83c\udf2f is \ud83d\udca6 so \ud83d\udcaf focused 1 \ud83c\udf84 economic efficency w/o \ud83d\udcad of \ud83d\udca6 social \ud83d\udcd6 consequences. \ud83d\ude4d That \ud83d\ude10 is \ud83d\udca6 not \ud83d\udeab the \ud83d\udc4f democratic \ud83d\udc34 way \ud83d\udcab &amp; \ud83d\ude45 ur \ud83d\udc56 not \ud83d\udeab socially liberal, \ud83d\udc68 ur \ud83d\udc56 socially libertarian. \ud83d\uddfd U \ud83d\udc48 do \ud83d\udc4c not \ud83d\udeab support \ud83d\udc96 social \ud83d\udcd6 justice, \ud83d\udc6e u \ud83d\udc48 insult it \ud83d\udcaf by \ud83d\ude08 claiming so. \ud83d\udcaf Ur \ud83d\udc56 beliefs r \ud83d\ude02 more \ud83c\udf57 in \ud83d\udc4f line \ud83d\udcc8 with \ud83d\udc4f republicans who \ud83d\ude02 don't \ud83d\udeab give \ud83d\udc49 \ud83c\udd70 \ud83c\udffb shit \ud83d\udca9 about \ud83d\udca6 social \ud83d\udcd6 justice \ud83d\udc6e so \ud83d\udcaf \ud83d\ude4f join \ud83d\udc4c them. \ud83d\udca6\n\n\ud83c\udd7f. S. \ud83d\ude02 U \ud83d\udc48 guys \ud83d\udc68 remind of \ud83d\udca6 joe manchin who \ud83d\ude02 is \ud83d\udca6 \ud83c\udd70 \ud83c\udffb democrat \ud83d\udc34 in \ud83d\udc4f name \ud83d\udcdb only \ud83d\udd66 he \ud83d\udc68 almost \ud83d\udcb8 always \ud83d\udd25 votes \ud83d\udd1d with \ud83d\udc4f the \ud83d\udc4f republican \ud83d\udc6f \ud83c\udf89 \ud83d\ude4f join \ud83d\udc4c them \ud83d\udca6",
            "created_utc": 1511460923,
            "id": "dq8slos",
            "link_id": "t3_7ezjpu",
            "parent_id": "t3_7ezjpu",
            "permalink": "/r/neoliberal/comments/7ezjpu/discussion_thread_automation_has_failed_us_yet/dq8slos/",
            "retrieved_on": 1511460924,
            "score": 1,
            "stickied": false,
            "subreddit": "neoliberal",
            "subreddit_id": "t5_2sfn3"
        },
        {
            "author": "KSDem",
            "author_flair_css_class": null,
            "author_flair_text": "I'm not a Heather; I'm a Veronica",
            "body": "&gt; Let's see how long Selebius is able to stick to her guns.\n\nSebelius is one of the rare Democrats of her generation (she's 69) who owes exactly *nothing* in her political career to either Clinton.  \n\nThe quintessential centrist, Sebelius is the daughter of former U.S. Congressman and Ohio Governor John Gilligan (a Democrat), and the daughter-in-law of former Kansas U.S. Congressman Keith Sebelius (a Republican).  Her husband's an attorney who's spent his career out of both politics and the limelight while she worked her way up in Kansas politics, first serving for 8 years in the Kansas House of Representatives, then as Insurance Commissioner for another 8 years (a position that, for women at least, has historically held more political sway in Kansas than one might think), and then 8 years as governor. \n\nSebelius' only significant political IOU is to Obama.  As governor of Kansas, she supported him over Clinton in the 2008 Kansas caucus, and he boosted her burgeoning national profile (she provided the Democratic response tothe 2008 State of the Union speech) by appointing her Secretary of HHS.  Her oversight of the (predictably) disastrous Obamacare rollout is the only significant stain on what was otherwise a very solid political career.  After that, she's had the common sense and political savvy to keep a low political profile.\n\nI've crossed paths with both Kathleen and her husband for decades and my assessment is this:  She's solid, like an oak.  She picks her battles, but is consistent with respect to her policy positions and she holds her ground even under significant political pressure.  \n\nFor those seeking a Democratic woman candidate with generally centrist views who's politically seasoned but generally unsullied either by association with the Clintons or the DC \"swamp,\" who resonates with establishment Democrats and moderate Republicans and is not so far removed from working class Americans that she no longer understands or relates to them, and who will bring a steady, practiced hand to the helm, she's your candidate.  While I don't think Sebelius has any particular aspirations she is, much like Joe Biden, kind of hiding in plain sight.",
            "created_utc": 1511457174,
            "id": "dq8ph5f",
            "link_id": "t3_7eytln",
            "parent_id": "t1_dq8gshd",
            "permalink": "/r/WayOfTheBern/comments/7eytln/if_theres_a_special_place_in_hell_for_women_who/dq8ph5f/",
            "retrieved_on": 1511457175,
            "score": 1,
            "stickied": false,
            "subreddit": "WayOfTheBern",
            "subreddit_id": "t5_3ff8l"
        },
        {
            "author": "pm_me_ur_fs",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Willing to talk.  Trump supporter,  moderate Republican.  Working class.  What would you like to talk about?",
            "created_utc": 1511454989,
            "id": "dq8nq2u",
            "link_id": "t3_7eysrg",
            "parent_id": "t1_dq8msvc",
            "permalink": "/r/4chan/comments/7eysrg/university_of_california_is_declaring_war_on_4chan/dq8nq2u/",
            "retrieved_on": 1511454990,
            "score": 1,
            "stickied": false,
            "subreddit": "4chan",
            "subreddit_id": "t5_2qh4w"
        },
        {
            "author": "atomic1fire",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I slightly disagree, in that Trump paid more attention to swing states then Hillary did, and he rallied republican voters more then Hillary could rally together democrats.\n\nHad Hillary picked Bernie as VP, she might have had a stronger chance of rallying the democrats behind her.\n\nTrump's choice of Pence warmed republicans who thought he was too moderate or unrepublican for the presidency.\n\nA vp either has to sell a president to moderates by being a moderate choice, or sell a moderate president to idealogues by being a unmoderate choice.\n\nHillary banked on a completely forgetable moderate who was unscandalous to the point that nobody cared about him, while Trump picked the guy people could hate, but he did a good job of keeping the scrutiny off Pence.",
            "created_utc": 1511452751,
            "id": "dq8lz0t",
            "link_id": "t3_7esrgh",
            "parent_id": "t1_dq87zp7",
            "permalink": "/r/Prematurecelebration/comments/7esrgh/i_seriously_cannot_think_of_a_title_for_this_post/dq8lz0t/",
            "retrieved_on": 1511452753,
            "score": 1,
            "stickied": false,
            "subreddit": "Prematurecelebration",
            "subreddit_id": "t5_2xkpe"
        },
        {
            "author": "truspiracy",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "&gt;If Al Franken resigns, his replacement is appointed by a Democratic governor and the Democrats retain the seat\n\nAl Franken barely squeaked in. Now that he is popular and now that he has nailed Jefferson Sessions in what appears to be perjury, his removal will have profound political consequences. His Democratic replacement will not likely be able to match his power in those early years. \n\n&gt;would have 2+ years as an incumbent to build support for retaining it.\n\nA special election will be held in 2018, and there is no guarantee that the Democrat will win in this relative swing state.\n\n&gt;Democrats presumed the seat was un-winnable, \n\nThe question of 'winnability' was on the table before the allegations, and some thought the seat was worth competing for, and would have done so. Considering the amount of time remaining when the allegations showed up, we will never know for sure. We can only say what appeared likely.\n\n&gt;the particular Democrat that would occupy the seat isn't remotely a mainstream Alabama candidate.\n\nThe particular Democrat is a moderate and was placed there precisely to be the most \"mainstream\" candidate considering the state.\n\n&gt; because he'd just be replaced by another Democrat, they're abandoning him in favor of the optics \n\nWho is \"they\"? This is a conclusion that we have not reached and that we may never reach. Let the investigation go forward. \n\nFinally, to reiterate: there is no guarantee that the Al Franken seat will stay Democratic at the next special election. It is more likely that the Jefferson Sessions seat will stay (or go) Republican in the 2020 election.\n\n\n\n",
            "created_utc": 1511452649,
            "id": "dq8lw98",
            "link_id": "t3_7f04gc",
            "parent_id": "t1_dq8k2pp",
            "permalink": "/r/politics/comments/7f04gc/two_more_women_accuse_franken_of_inappropriate/dq8lw98/",
            "retrieved_on": 1511452650,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "staomeel",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "&gt;Yeah it is normal. \n\nThen why argue in the /r/justicedemocrats if you don't support our values?  It's literally rule #1, Justice Democrats don't take bribes from corporations and millionaires. There are so many democratic subreddits not bothered by corruptions.  They'd love to have you.\n\n&gt;He donated to other Democraric politicians as well long beforehe was a reviled Republican nominee.\n\nA racist, homophobic, misogynist millionaire was buying favors from Democrats past and preset, your not bothered by that?  We are here to fight all these things.  Why are you here?\n\n&gt;You seem to be grasping at straws when we can point to strong progressive actions as AG and as a senator.\n\n&gt;Mnuchin is Donald Trump\u2019s nominee to run the Treasury Department, and served as CEO of OneWest from 2009 to 2015. In an internal memo published on Tuesday by The Intercept, **prosecutors at the California attorney general\u2019s office said they had found over a thousand violations of foreclosure laws by his bank during that time, and predicted that further investigation would uncover many thousands more.**\n\nSteve Mnuchin isn't behind bars because Kamala Harris didn't want to investigate the other owner of OneWest bank.  It's simple math.  The elite stomped on Californian's guts and Kamala let them do it, over and over again.  Not a single prosecution was brought to trial despite the dump trunk full of evidence against OneWest bank.  That's criminal negligence. That's Kamala Harris.\n\n&gt; One of the top progressive records in all og congress.\n\nIf your only paying attention to her congressional record your acting willfully ignorant.\n\n&gt;She's not Bernie. Few, if any, ever will be. But she's right there with people lije Warren and Ellison fighting for strong progressive values.\n\nWarren and Ellison are moderate conservatives at best.  Justice Democrats will take their jobs assuming they don't lose their spine and start taking bribes.\n",
            "created_utc": 1511431981,
            "id": "dq8bja5",
            "link_id": "t3_7ekr58",
            "parent_id": "t1_dq85swx",
            "permalink": "/r/justicedemocrats/comments/7ekr58/my_representative_kamala_harris_takes_money_from/dq8bja5/",
            "retrieved_on": 1511431982,
            "score": 1,
            "stickied": false,
            "subreddit": "justicedemocrats",
            "subreddit_id": "t5_3iqju"
        },
        {
            "author": "ecodude74",
            "author_cakeday": true,
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "You're being downvoted but even as a damn socialist liberal you're right. I've known people who wanted lower taxes and less spending on welfare for years suddenly turn into racists and homophobes in recent years. Good people, who'd give you the shirt off their back, now want to declare war on damned near everyone. The modern Republican Party isn't what most conservatives ever wanted, but radical ideology combined with economic downturn have wrecked any semblance of moderate conservatism the party clung to like a life preserver. It's sad really how bad things have gotten for this country. ",
            "created_utc": 1511429930,
            "id": "dq8atia",
            "link_id": "t3_7es7v8",
            "parent_id": "t1_dq7u9q6",
            "permalink": "/r/lgbt/comments/7es7v8/wont_somebody_think_of_the_children/dq8atia/",
            "retrieved_on": 1511429931,
            "score": 1,
            "stickied": false,
            "subreddit": "lgbt",
            "subreddit_id": "t5_2qhh7"
        },
        {
            "author": "gometrule",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "&gt; \n&gt; But at the same time, not all of those states had the outcomes affected by third party voters - it's still not fair to blame the loss entirely on them.\n\nI'm not saying they should be entirely blamed for anything. They're just among the groups who get some of the blame. \n\n&gt;I've seen very little from the actual DNC admitting that they may have made any mistakes in the election or pushes to improve themselves\n\nIt's out there. They've acknowledged it.\n\nhttps://www.huffingtonpost.com/entry/tom-perez-dnc-chair-reform-presidential-nominating-process_us_59fe7f2de4b0c9652fffc12d\n\n&gt;Don't know if they still have traction, but a few months ago there were campaigns to unseat Sanders in 2018 and to prevent progressive candidates from taking any seats. \n\nI haven't heard about it. I have heard and seen the other side doing this instead though. I regularly see candidates doing AMAs and trying to use the Sanders subreddits to attack moderate Dems they want to primary.\n\n&gt;My current fear is that we're going to lose horribly in 2018 due to this petty split in the democratic party, and right now the cause of that split is largely one sided.\n\nI mean, I would say it's largely one-sided too, but probably in the other direction than you would. I've never seen anyone seriously suggest they should try to knock Bernie out in Vermont. I do see progressives trying to knock off moderate Dems even in places where a progressive would have no chance to win like in WV. I haven't seen Hillary supporters give ultimatums for when they're willing to vote. I have seen that from a number of Bernie supporters. In the primary, I saw Bernie supporters make it their mission to attack Hillary. They posted propaganda from RT, Breitbart, and any other site they could fine. If it attacked Hillary, that was the only qualification. I didn't see the same from the other side. \n\nIf we want to win in 2018 and in 2020 and beyond, we just have to be united. Agree that regardless of whose candidate wins the primary, we all work together to elect the Democrat. Even if they weren't our top choice, they will be far better for the country than a Republican would be. ",
            "created_utc": 1511424611,
            "id": "dq88sem",
            "link_id": "t3_7ewcvw",
            "parent_id": "t1_dq88ial",
            "permalink": "/r/politics/comments/7ewcvw/im_on_the_fcc_please_stop_us_from_killing_net/dq88sem/",
            "retrieved_on": 1511424612,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "childishgames",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I've always been a slightly left leaning, cynical, snarky, and opinionated guy, but Reddit just makes me so one sided. Reddit makes me so much worse.. and I think that's an issue. Any opposing side gets downvoted to hell. \n\nI can't ever find any logical, valid conservative/Republican points of view on this site... It's either the standard liberal stuff or some crazy red pill, the_Donald extreme shit that is batshit insane.  I wish there were more moderate sources I could be exposed to regularly",
            "created_utc": 1511424206,
            "id": "dq88m6o",
            "link_id": "t3_7eucth",
            "parent_id": "t3_7eucth",
            "permalink": "/r/selfimprovement/comments/7eucth/how_can_i_become_less_opinionated_cynical_and/dq88m6o/",
            "retrieved_on": 1511424207,
            "score": 1,
            "stickied": false,
            "subreddit": "selfimprovement",
            "subreddit_id": "t5_2qmbm"
        },
        {
            "approved": false,
            "author": "Atomhed",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Trump *is* selling out to big business, he is pushing for the removal of net neutrality.\n\nAnyway, as I said, I am not debating here, and I'm not going to respond as if I am. I believe you'd have to have been very purposefully obtuse to not grasp that my comment about Iraq, Afghanistan, and Republican wars were in response to what you said about how we failed to help those countries. It's obtuse to say America has never helped countries by referring to two countries we were at war with.\n\nAnd while the war in Afghanistan was a war on terror, the one in Iraq was not.\n\nIf this were any other day I'd be down to get into a much more nuanced conversation with you, but this is a peaceful week for me, and my favorite holiday. I would not prefer to debate, however, as a debate requires a winner and a loser, and I am merely looking for understanding. On top of that, I'm fairly certain that 99 percent of the people on reddit who say that they are trying to have a debate don't actually know how to debate, or what a debate *is*.\n\nHere's some food for thought, in debate in college, we would be given positions to defend in debate. We were not speaking about our own ideas, we were learning how to understand logic other than our own. My goal here is to be able to enter a debate and defend **your** position, in my own words, in a way that is satisfactory to you. That means I understand you, where you're coming from, and from there we can break through this two party system.\n\nPerhaps I'm old school, but as a Conservative Democrat, I really wish more people were true middle lane. Hell, the DNC itself leans to the right. What \"we\" currently referr to as \"the left\" is actually quite moderate. The GOP is the party of extremes. \n\nAnyway, I'm not typing this because I'm trying to debate you, I'm hoping that next time we run into one another you may understand my intentions and what I mean when I tell you I'm speaking in good faith.\n\nAnd for the record, I am that way inherently, I've been this way my whole life, I'm not participating in good faith because I just learned about that concept let year, and I'm not trying to understand because I am all of a sudden into politics since 2015. This is just me, and if I wasn't concerned about anonymity I would link you to various things I've written over the years that show exactly that.\n\nSo, I *am* sorry that I don't have the time to debate you, and I'm sorry I don't have the time to quote you, but from my side, this has only been a conversation.\n\nEnjoy your Thanksgiving, and have a good long weekend.",
            "created_utc": 1511423799,
            "id": "dq88fw3",
            "ignore_reports": false,
            "link_id": "t3_7eq76i",
            "parent_id": "t1_dq87wef",
            "permalink": "/r/POTUSWatch/comments/7eq76i/potus_on_twitter_rt_realjmannarino/dq88fw3/",
            "removed": false,
            "retrieved_on": 1511423800,
            "score": 1,
            "spam": false,
            "stickied": false,
            "subreddit": "POTUSWatch",
            "subreddit_id": "t5_3jgtl"
        },
        {
            "author": "comix_corp",
            "author_flair_css_class": "lebanon",
            "author_flair_text": "Lebanon",
            "body": "HuffPost rose like any other modern corporate media outlet did. It's rise was actually pretty similar to the rise of Breitbart. It's not particularly weird and it's not indicative of any leftism among the American establishment.\n\nObama himself was not very left wing. Illegal drone strikes, immense support for brutal dictatorships like the KSA, overwhelmingly pro-corporate economic policies, totalitarian spying on the world's citizens, etc. Leftists hate all of these things.\n\nI mean he literally said\n\n&gt; [The truth of the matter is that my policies are so mainstream that if I had set the same policies that I had back in the 1980s, I would be considered a moderate Republican.](http://thehill.com/policy/finance/272957-obama-says-his-economic-policies-so-mainstream-hed-be-seen-as-moderate-republican-in-1980s)\n\n",
            "created_utc": 1511420991,
            "id": "dq876gi",
            "link_id": "t3_7evits",
            "parent_id": "t1_dq85umb",
            "permalink": "/r/nrl/comments/7evits/league_immortal_on_child_abuse_charges/dq876gi/",
            "retrieved_on": 1511420992,
            "score": 1,
            "stickied": false,
            "subreddit": "nrl",
            "subreddit_id": "t5_2qn90"
        },
        {
            "author": "woowoo293",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Is your representative a Democrat or a Republican?  If a Republican, then moderate or conservative?  If anything other than moderate Republican, you may be wasting your time. ",
            "created_utc": 1511417997,
            "id": "dq85oyi",
            "link_id": "t3_7evz5o",
            "parent_id": "t1_dq848h3",
            "permalink": "/r/funny/comments/7evz5o/on_this_day_in_reddit_history/dq85oyi/",
            "retrieved_on": 1511417998,
            "score": 1,
            "stickied": false,
            "subreddit": "funny",
            "subreddit_id": "t5_2qh33"
        },
        {
            "author": "quix117",
            "author_flair_css_class": "yellen image",
            "author_flair_text": "Janet Yellen",
            "body": "name one democrat economic policy that this sub supports. Almost every thread I see supports only republican I do not see a single thread supporting any democratic policies and whenever I bring up liberal policies you guys denounce. No guys are not center left. Your goal is to ensure the minimum standard of living while being hyper focused on supporting economic efficency with little thought to that is not center left that is center right. Center right=vigirously support economic efficency while throwing a few bread crumbs at the poor. Center left=support maximum standard of living in a fically efficent, responsible and pragmatic manner. This sub is focused on economic effiency I have literally seen threads talking about whether welfare for starving people is in of itself economically effiecent and is better to just hand poor coal miners welfare checks over retraining them because it would economically more efficent. Progress at all expenses is what this sub is. Also this sub claims to be socially liberal, however, it is not. You cannot be socially liberal without being somewhat economically left wing. Why? social liberalism seeks to solve social ills while this sub seems to not give a fuck about them since to do so you need to spend money on poor people when litterally your policies argue for the opposite ex. rampant hate of unions which literally are the reason why blue states have a much lower rate of industrial accident deaths than red states (you cannot seperate one from the other). In reality people here are social libertarians. In that they claim to be all progressive and oh i accussed you of ableism but when push comes to shove you are not a true social justice warrior. You cannot seperate economic issues and social issues like this sub tries to do. Overall I do tend to support a lot of the economic policies except on certain key issues ex. unions, labor laws, healthcare, net neutrality, free community college. Overall while its fine to have the policy positions you guys have to claim to be a democrat pisses. Most of your economic positions are often opposite of democrat and more often than not you support the republicans on almost every issues with maybe a few breadcrumbs thrown at the poor so you can feel a little more socially liberal when you are not.\nPolitical Positions\nCenter Right (ex. Nelson Rockefeller)-neoliberal-you guys are really Rockefeller Republicans (republican lite), ex. Manchin\nCentrist (ex. Bill Clinton)-at heart Bill Clinton was center left but had to be more fiscally conservative since america was very fiscally conservative at the time and congress was majority republican\nCenter Left (ex. Obama, Hillary Clinton etc.)-actual social liberals-fiscally center-left-these people have left wing ideals but are pragmatic pro market approach in achieving them. they support creating maximum level of living standard for most people but take pragmatic approach while seeking maintain strong economy. Obama appearred to be a centrist because republicans blocked his more left wing policy proposals.\nLeft (ex. Bernie Sanders, Jeremy Corbyn)-Have same goals as center left but take less pragmatic, more government oriented and tend to demonize anybody who is left wing.\nBtw did you know? Bill Clinton increased top marginal tax rate, corporate tax rate, capital gains tax rate, housing assistance doesn't sound very neoliberal.\nThe fact of the matter is you can believe what you want but please stop calling yourself a democrat or a moderate democrat because you are not litterally in this sub I see most people supporting republican policies and bashing democratic policies. How can you call yourself a democratic when you litterally in this sub people supported Romney who wanted to end Obamacare, reduce environmental regulations, increase tarrifs on china. \nOverall this sub is so focused one economic efficency without thought of social consequences. That is not the democratic way and no you are not socially liberal, you are socially libertarian. You do not support social justice, you insult it by claiming so. Your beliefs are more in line with republicans who don't give a shit about social justice so please join them.  \nP.S. You guys remind of Joe Manchin who is a democrat in name only he almost always votes with the republican party please join them",
            "created_utc": 1511415117,
            "id": "dq842vz",
            "link_id": "t3_7ehbgr",
            "parent_id": "t1_dq6f78j",
            "permalink": "/r/neoliberal/comments/7ehbgr/discussion_thread_government_monopoly_edition/dq842vz/",
            "retrieved_on": 1511415118,
            "score": 1,
            "stickied": false,
            "subreddit": "neoliberal",
            "subreddit_id": "t5_2sfn3"
        },
        {
            "author": "Poolboy24",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "I agree Pai is a concern, but Obama brought him into the FCC.\n\nWe need to stop seeing this as a left vs right, red vs blue and start seeing it for what it is: people who are looking to subjucate Americans for profit and those looking to defend the rights and civil life of their countrymen.\n\nI won't lie right now the Republican party has been overrun with special interests, business and religious/racial extremes, but that does not mean there is a large conservative and moderate group that doesn't disagree with their talking heads.\n\nFuck healthcare, your gender or the war, we can agree as Americans free internet is tantamount to life liberty and the pursuit of happiness.",
            "created_utc": 1511402313,
            "id": "dq7v0qs",
            "link_id": "t3_7ev42z",
            "parent_id": "t1_dq7tn9i",
            "permalink": "/r/worldnews/comments/7ev42z/justin_trudeau_is_very_concerned_with_fccs_plan/dq7v0qs/",
            "retrieved_on": 1511402314,
            "score": 1,
            "stickied": false,
            "subreddit": "worldnews",
            "subreddit_id": "t5_2qh13"
        },
        {
            "author": "uptvector",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Take the low road and Republicans will win 10 times our of ten out of years of experience. That\u2019s like a Republican saying that they can beat Dems on women\u2019s issues.\n\nAnd you\u2019ll lose moderate voters who will stay stay at home.",
            "created_utc": 1511401887,
            "id": "dq7uowt",
            "link_id": "t3_7evkay",
            "parent_id": "t1_dq7ubf5",
            "permalink": "/r/politics/comments/7evkay/two_more_women_accuse_sen_al_franken_of/dq7uowt/",
            "retrieved_on": 1511401888,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "omid_",
            "author_flair_css_class": null,
            "author_flair_text": "12\u2206",
            "body": "But the article goes into this:\n\n&gt;&gt;The other problem is that the term \"moderate\" makes it sound like there's one kind of moderate \u2014 which is where the idea emerges that there's some silent moderate majority out there waiting for their chance to take back politics. But someone who believes in punitively taxing the rich and criminalizing homosexuality is not going to form a coalition with someone who believes in low taxes and gay marriage, even though both of these voters would look moderate on a survey.\n\n&gt;&gt;The deeper point here is that the idea of the moderate middle is bullshit: it's a rhetorical device meant to marginalize some policy positions at the expense of others. There's no actual way to measure it, or consistent definition animating it, and it doesn't spontaneously emerge in any of the data.\n\nVoter suppression aside, what we got in the form of Clinton and Trump really is what a plurality of Americans want. Turnout was about 55%, so the combined total of Clinton + Trump votes represents just over half of Americans, which is in line with [the 55% of Americans who identify as either Republican or Democrat](http://news.gallup.com/poll/15370/party-affiliation.aspx). Again, keep in mind that what the news organizations push as the \"sides\" is not necessarily what the average American likes. This is why the corporate media was totally clueless about why Trump and Sanders had such core support.",
            "created_utc": 1511400679,
            "id": "dq7troc",
            "link_id": "t3_7etymr",
            "parent_id": "t1_dq7stem",
            "permalink": "/r/changemyview/comments/7etymr/cmv_american_political_parties_specifically_the/dq7troc/",
            "retrieved_on": 1511400681,
            "score": 1,
            "stickied": false,
            "subreddit": "changemyview",
            "subreddit_id": "t5_2w2s8"
        },
        {
            "author": "REdEnt",
            "author_flair_css_class": null,
            "author_flair_text": "Brooklyn Heights",
            "body": "Ok, great, what the hell else am I\ufe0f supposed to do? Cuomo, for New York State, is essentially a moderate republican; there\u2019s barely a difference between him and his opponent (it\u2019s not like his opponent is going to ban abortion or gay marriage; sure, they maybe be opposed to it, but they literally run on the stance **that they won\u2019t change anything about it.**\n\nAnd yeah, vote in the primaries, I\ufe0f did.\n\nAnd furthermore the \u201callied Democrats\u201d are literally just Republicans disguised as Democrats, and our Democrat governor will do nothing to call them out. Hell, **he capitulates to them**.",
            "created_utc": 1511399611,
            "id": "dq7sy5l",
            "link_id": "t3_7erjm1",
            "parent_id": "t1_dq6wjep",
            "permalink": "/r/nyc/comments/7erjm1/who_to_blame_for_your_subway_nightmareheres_a/dq7sy5l/",
            "retrieved_on": 1511399612,
            "score": 1,
            "stickied": false,
            "subreddit": "nyc",
            "subreddit_id": "t5_2qhu2"
        },
        {
            "author": "REdEnt",
            "author_flair_css_class": null,
            "author_flair_text": "Brooklyn Heights",
            "body": "Ok, great, what the hell else am I\ufe0f supposed to do? Cuomo, for New York State, is essentially a moderate republican; there\u2019s barely a difference between him and his opponent (it\u2019s not like his opponent is going to ban abortion or gay marriage; sure, they maybe be opposed to it, but they literally run on the stance **that they won\u2019t change anything about it.**\n\nAnd yeah, vote in the primaries, I\ufe0f did.",
            "created_utc": 1511399442,
            "id": "dq7stk7",
            "link_id": "t3_7erjm1",
            "parent_id": "t1_dq6wjep",
            "permalink": "/r/nyc/comments/7erjm1/who_to_blame_for_your_subway_nightmareheres_a/dq7stk7/",
            "retrieved_on": 1511399443,
            "score": 1,
            "stickied": false,
            "subreddit": "nyc",
            "subreddit_id": "t5_2qhu2"
        },
        {
            "author": "mitchluvscats",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Honestly I don't know what I would do if it were the other way around. The democrat would have to be pretty damn bad and the republican would have to be moderate for me to consider switching my vote. Otherwise I just wouldn't vote. ",
            "created_utc": 1511398318,
            "id": "dq7ryww",
            "link_id": "t3_7eulqt",
            "parent_id": "t3_7eulqt",
            "permalink": "/r/politics/comments/7eulqt/when_democrat_is_a_worse_slur_than_alleged_sexual/dq7ryww/",
            "retrieved_on": 1511398319,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "badfordabidness",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "If anything, what we\u2019ve witnessed since November should be sufficient proof that Obama was *never* \u201cRepublican-lite\u201d in the first place.\n\nEven the most moderate Republicans, like Murkowski, will throw healthcare and the middle class under the bus without a second thought.\n\nMurkowski and Collins could aptly be called \u201cRepublican lite.\u201d Obama **cannot** be put in that same category by any reasonable person.\n\nObama tried to build up this country and affect positive change (however incremental) for all Americans. Republicans, whether \u201clite\u201d or radical, are only interested in tearing our society and it\u2019s safety net to shreds.",
            "created_utc": 1511398255,
            "id": "dq7rx4l",
            "link_id": "t3_7evkay",
            "parent_id": "t1_dq7rbnq",
            "permalink": "/r/politics/comments/7evkay/two_more_women_accuse_sen_al_franken_of/dq7rx4l/",
            "retrieved_on": 1511398257,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "LoveTrumpedHate",
            "author_flair_css_class": "non",
            "author_flair_text": "Nimble Navigator",
            "body": "&gt; Even though Roy Moore acknowledges them?\n\nThis makes it reliable.\n\n&gt; they have been reported by Mass Media?\n\nThis doesn't mean anything.\n\n&gt; Corollary, what news sources do you trust?\n\nExactly none of them, are you joking?  At best they're all biased and at worst they're CNN.  If your anchor openly wept on live TV when Trump won, do not trust their opinions to be moderate.\n\nWhen I see a story, for example Net Neutrality, I'll read different sides from different sources and as a rule of thumb accept incompetence before malevolence.\n\nAs to Roy Moore, I absolutely don't care.  Not my circus not my monkeys.  I'm not even a republican, let alone an Alabaman.  I can't do anything about him either way, so why get emotionally invested.\n\nI mean at least I can stop going to Ben Affleck movies.",
            "created_utc": 1511394683,
            "id": "dq7p5f6",
            "link_id": "t3_7etp91",
            "parent_id": "t1_dq7osk3",
            "permalink": "/r/AskTrumpSupporters/comments/7etp91/do_you_believe_that_republicansconservatives_hold/dq7p5f6/",
            "retrieved_on": 1511394684,
            "score": 1,
            "stickied": false,
            "subreddit": "AskTrumpSupporters",
            "subreddit_id": "t5_3cr3o"
        },
        {
            "author": "SaintBerntard",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "&gt; I self-identify as an Independent though on this sub I'm probably more left than most\n\nI just want to make the point that even if you self-identify as an Independent, you should still register for a party. Its usually very easy (I do it online in my state). I register Republican in years when I want to influence that platform, and Democrat when I want to influence their platform. For instance, my state GOP essentially cancelled the state caucus last year, so I'm actually a registered Democrat so that I could vote Clinton over Sanders. Next year I'll probably switch back to a Republican registration since my incumbent Representative is a Democrat, so I'd like a voice in choosing a moderate to run against him.\n\nRegistering as a member of a party doesn't mean you aren't an Independent IMO, it just gives you a voice in choosing moderate candidates for the general election.",
            "created_utc": 1511393089,
            "id": "dq7nx24",
            "link_id": "t3_7er7p9",
            "parent_id": "t1_dq6x1f7",
            "permalink": "/r/tuesday/comments/7er7p9/to_the_republicans_and_independents_here_why_not/dq7nx24/",
            "retrieved_on": 1511393090,
            "score": 1,
            "stickied": false,
            "subreddit": "tuesday",
            "subreddit_id": "t5_2r8s0"
        },
        {
            "author": "JeahNotSlice",
            "author_flair_css_class": "Raptors6",
            "author_flair_text": "[TOR] Carlos Rogers",
            "body": "Not an American, but curious: is there scope for an \"anti-trump\" republican candidate in red states? Someone who will be palatable to moderate republicans (pro life, conservative, aw shucks one-of-the-folks) but is prepared to say \"this crony-ist sell out is not my president\" and hold him to account from within the party/ legislature? ",
            "created_utc": 1511392471,
            "id": "dq7nftg",
            "link_id": "t3_7es0x3",
            "parent_id": "t1_dq7kcaa",
            "permalink": "/r/nba/comments/7es0x3/daily_locker_room_and_free_talk_game_threads/dq7nftg/",
            "retrieved_on": 1511392473,
            "score": 1,
            "stickied": false,
            "subreddit": "nba",
            "subreddit_id": "t5_2qo4s"
        },
        {
            "author": "PowerBombDave",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Dems are pretty moderate, dude.  Reminder that socialist demonking Obama raised taxes like 4% on the rich and Clinton did more to obliterate welfare than any recent Republican because third way democrats are just neoliberals in the vein of Reagan.  I disagree with them primarily on social issues, but on economic policy they've kind of hoodwinked the GOP; you get all the insane hyperbole from conservative media labeling slight tax increases and moderate social program as stalinism because they can't attack the policies on their merits as they're not far removed from the GOP's own.  Obamacare is a good example of this considering its a pro-corporate answer to healthcare conceived by the heritage foundation, but is painted as wildly leftist nowadays.  If they would chill out on guns, abortion, etc they'd basically be the GOP of the 80s.",
            "created_utc": 1511389594,
            "id": "dq7l42v",
            "link_id": "t3_7er7p9",
            "parent_id": "t1_dq7gjhm",
            "permalink": "/r/tuesday/comments/7er7p9/to_the_republicans_and_independents_here_why_not/dq7l42v/",
            "retrieved_on": 1511389596,
            "score": 1,
            "stickied": false,
            "subreddit": "tuesday",
            "subreddit_id": "t5_2r8s0"
        },
        {
            "author": "ctdca",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "The problem is that, objectively, Obama's presidency was in many ways not all the much different from moderate mainstream Republican presidencies of prior decades. Obamacare was a Heritage Foundation proposal, originally championed by Mitt Romney. Past Republican presidents often championed environmental protections. Nixon signed the law creating the EPA. Obama's positions were not extreme or unusual; they were normal and expected.\n\nThis \"extreme damage\" is an invention. Anyone who believes that is absurdly out of touch with reality and deserves to be mocked.",
            "created_utc": 1511389371,
            "id": "dq7kxiv",
            "link_id": "t3_7eumvh",
            "parent_id": "t1_dq7kc4t",
            "permalink": "/r/politics/comments/7eumvh/this_thanksgiving_im_grateful_hillary_clinton_is/dq7kxiv/",
            "retrieved_on": 1511389372,
            "score": 1,
            "stickied": false,
            "subreddit": "politics",
            "subreddit_id": "t5_2cneq"
        },
        {
            "author": "cazort2",
            "author_flair_css_class": "purple image image-duck",
            "author_flair_text": "Moderate Weirdo",
            "body": "&gt; I think this is starting to break down lately, IMO. If the Republican party continues with the populist approach, they are in danger of losing their moderate and libertarian base.\n\nI agree and this concerns me.  It's like, I have thought of the GOP of needing a sort of change / reform for some time, but I really don't want the change to go in the direction that it went with the current sort of \"populism\"...it seems to be abandoning some of the aspects of conservatism that I find most attractive, notably, fiscal conservatism, while retaining or at least tolerating some of the more extreme socially conservative views.\n\nI also am very concerned with an authoritarian tendency or trend in the recent sort of populism.\n\n&gt; Some people at Cato consider themselves left-wing now, Reason, the beltway think-tanks, even the LP are being called \"left-libertarians\" and the paleos are \"right-libertarians.\n\nThis is weird and sad to me.  I really like both Cato and Reason.",
            "created_utc": 1511386827,
            "id": "dq7ipkc",
            "link_id": "t3_7er7p9",
            "parent_id": "t1_dq7cwoa",
            "permalink": "/r/tuesday/comments/7er7p9/to_the_republicans_and_independents_here_why_not/dq7ipkc/",
            "retrieved_on": 1511386828,
            "score": 1,
            "stickied": false,
            "subreddit": "tuesday",
            "subreddit_id": "t5_2r8s0"
        },
        {
            "author": "SchidtPosta",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "Moderate Republican (most of the time, I have a few views that align with Democrats) here. Can\u2019t speak for anyone else on my side of things, but I personally support net neutrality vehemently.",
            "created_utc": 1511386519,
            "id": "dq7ifb7",
            "link_id": "t3_7erver",
            "parent_id": "t1_dq7dmwu",
            "permalink": "/r/worldnews/comments/7erver/internet_defenders_urge_mass_revolt_to_fight_fccs/dq7ifb7/",
            "retrieved_on": 1511386521,
            "score": 1,
            "stickied": false,
            "subreddit": "worldnews",
            "subreddit_id": "t5_2qh13"
        },
        {
            "approved": false,
            "author": "MyRSSbot",
            "author_flair_css_class": null,
            "author_flair_text": "beep boop",
            "body": "**Rule 1:** Be civil and friendly, address the argument not the person, and don't harass or attack other users.\n\n**Rule 2:** No snark/sarcasm and no low-effort circle-jerky comments contributing nothing to the discussion.\n\n**Rule 3:** Overly-short comments that don't contain a question will be removed automatically.\n\nPlease don't use the downvote button as a 'disagree' button and instead just report any rule-breaking comments you see here.\n\n[[removed comments]](https://ceddit.com/r/POTUSWatch/comments/7eueys/a_democratic_senator_said_wednesday_that_white/)\n\nArticle:\n\n&gt;A Democratic senator said Wednesday that White House National Economic Council Director Gary Cohn told President Trump he had a bad cell connection as an excuse to stop talking to Trump.\n\n&gt;Sen. Tom Carper, who sits on the Senate Finance Committee, shared details of the meeting he attended with a group of moderate Democrats who discussed tax reform with Cohn and White House legislative affairs director Marc Short, while Trump joined by phone.\n\n&gt;\"I said to Gary, it was a room where we're all sitting around this big table, and I said, 'Gary, why don't you do this, just take the phone from, you know, your cellphone back and just say, Mr. President, you're brilliant. But we're losing contact, and I think we're going to lose you now, so good-bye.' And that's what he did and he hung up,\" Carper told CNN. Carper said the group of Democratic senators were looking to find common ground with the administration on taxes.\n\n&gt;\"We went back to having the kind of conversation where we needed to, where they ask a questions, looking for consensus, looking for. common ground, and I think we identified [that],\" he said.\n\n&gt;CNN host John Berman asked Carper to clarify if he was saying Cohn faked a bad connection to get the president off of the phone.\n\n&gt;\"Well I wouldn't ... I don't want to throw him under the bus, but yes,\" Carper replied.\n\n&gt;The White House pushed back on Carper's claim on Wednesday, calling it false.\n\n&gt;\"Senator Carper's claim is completely false. Gary Cohn took the phone off speaker and continued to speak with the president privately for several minutes before they concluded the call,\" White House principal deputy press secretary Raj Shah said in a statement to The Hill.\n\n&gt;Carper revealed in an interview with The Hill earlier this month that he told Cohn to fake a bad connection during the call so the Democratic senators could \"Have a real conversation\" with the Trump administration officials who attended the meeting.\n\n&gt;Trump \"Was ready to talk and talk and finally after 15 minutes\" Carper said he turned to Cohn to tell him, \"We're not going to have a real conversation here - can't you just tell the president that he is brilliant and say we're losing ... the connection and then hang up?\".\n\n&gt;Republicans have been pushing for tax reform as they look to secure their first major legislative victory during Trump's tenure.\n\n&gt;Democratic senators have clashed with their GOP counterparts on the legislation.\n\n&gt;Sen. Bernie Sanders , who caucuses with Democrats, said on Sunday that Senate Democrats have been completely shut out of the process.\n\n&gt;Trump has said Democrats have been unwilling to work with their Republican counterparts, calling them \"Obstructionists.\"",
            "created_utc": 1511385915,
            "id": "dq7huxy",
            "ignore_reports": false,
            "link_id": "t3_7eueys",
            "parent_id": "t3_7eueys",
            "permalink": "/r/POTUSWatch/comments/7eueys/a_democratic_senator_said_wednesday_that_white/dq7huxy/",
            "removed": false,
            "retrieved_on": 1511385917,
            "score": 1,
            "spam": false,
            "stickied": false,
            "subreddit": "POTUSWatch",
            "subreddit_id": "t5_3jgtl"
        },
        {
            "author": "MikeAWBD",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "If they want to keep power after they get it they need to.  After this, I think there are a lot of long time republicans that might be willing to switch sides.  I voted almost exclusively republican my entire life.  I will be voting democrat in the mid-term and the next presidential election.  If dems want to keep my vote after that they will need to moderate. There are probably a lot of younger gen x/millennial republicans like me that feel the same.",
            "created_utc": 1511384462,
            "id": "dq7gjhm",
            "link_id": "t3_7er7p9",
            "parent_id": "t1_dq7e4fw",
            "permalink": "/r/tuesday/comments/7er7p9/to_the_republicans_and_independents_here_why_not/dq7gjhm/",
            "retrieved_on": 1511384464,
            "score": 1,
            "stickied": false,
            "subreddit": "tuesday",
            "subreddit_id": "t5_2r8s0"
        },
        {
            "author": "KallistiEngel",
            "author_flair_css_class": null,
            "author_flair_text": "Downtown",
            "body": "Tom Reed doesn't give a damn about anything but his own wallet and he makes that clear time and time again.\n\nWhy does anyone give this guy a pass? Republicans, I'm not asking you to vote Democrat, but seriously try to weed guys like Reed out of your party. I'm not a Republican, but I'd vote for a moderate Republican that had some integrity, especially if it meant ousting Reed.",
            "created_utc": 1511383179,
            "id": "dq7fcv3",
            "link_id": "t3_7er31b",
            "parent_id": "t3_7er31b",
            "permalink": "/r/ithaca/comments/7er31b/residents_berate_rep_tom_reed_over_house_tax_bill/dq7fcv3/",
            "retrieved_on": 1511383195,
            "score": 1,
            "stickied": false,
            "subreddit": "ithaca",
            "subreddit_id": "t5_2rp73"
        },
        {
            "author": "cgmcnama",
            "author_flair_css_class": null,
            "author_flair_text": null,
            "body": "#######On Sanders:\n\nLike I said, Bernie wasn't close.  You don't win the parties seat by winning the most states, you win them by winning the most delegates and that comes from votes.\n* Clinton beat Sanders by 359 delegates (884 if you count superdelegates) and over 1,000 if they used the winner take all rules of the Republican party.  \n* In the popular vote, Clinton would have won by 12 percentage points.  A landslide by any kind of election race. (16.8 million to 13.2)\n* And taking history into account, these numbers would actually have been higher if Sanders dropped out when most candidates realize they cannot win.  \n* The race was over after Super Tuesday.  Clinton actually spent less then Sanders in the second half of the race and had virtually no negative ads run against Sanders which would have also inflated the popular vote.  She was looking ahead and wanted his backers.\n\n######On McCain:\n\nThis whole \"outsider\" and \"establishment\" meaning has really shifted after this last campaign.  Because most delegates have some political experience before Obama, it meant whether you voted or agreed, lockstep with your party.  McCain was branded, and embraced, being a maverick by his party for a reason.  He reportedly was going to even choose a Democratic VP before it got leaked and sank those chances.  Republicans were hoping he was moderate enough to get the swing voters and it obviously didn't work.\n\n######On Trump in 2020\n\nYou can always beat the odds.  But the odds are the incumbent US president has a historical advantage in running again.  And he already started fund raising for 2020 a month after he won the election.  The Democrats don't even have a candidate.\n\nYour logic is the same Republicans used in the lead up to 2012.  That Obamacare is so awful  that a Republican must be elected.  And of course they had the \"momentum\" of Midterms when they controlled the House and Senate in 2010.  The Democrats \"momentum\" right now is winning at the local level in two states.  Just a reminder to keep things in perspective.",
            "created_utc": 1511381745,
            "id": "dq7e1gi",
            "link_id": "t3_7el9bs",
            "parent_id": "t1_dq6zmpm",
            "permalink": "/r/PoliticalHumor/comments/7el9bs/bbbbut_bernie/dq7e1gi/",
            "retrieved_on": 1511381753,
            "score": 1,
            "stickied": false,
            "subreddit": "PoliticalHumor",
            "subreddit_id": "t5_2qm21"
        },
        {
            "author": "veriworried",
            "author_flair_css_class": "purple",
            "author_flair_text": "bleeding-heart libertarian/neoclassical liberal",
            "body": "Good post, I think this captures a lot of people's reasoning.\n\nI try very hard not to be associated with the right, or Republicans, but it's hard to deny the fact that the GOP has been a more hospitable to people like me (moderate libertarian, classical liberal, whatever label you want to use) historically.\n\n&gt; whereas Republicans seem to favor a more unified approach.\n\nI think this is starting to break down lately, IMO. If the Republican party continues with the populist approach, they are in danger of losing their moderate and libertarian base. The libertarian \"world\" is actually going through some pretty bad infighting right now (it's always been there, but it's flared up recently with the chairman of the LP calling the LvMI the \"preferred choice of nazis\"). Some people at Cato consider themselves left-wing now, Reason, the beltway think-tanks, even the LP are being called \"left-libertarians\" and the paleos are \"right-libertarians.\" I think this might be a symptom of libertarians feeling alienated from the GOP (and the paleo's support of Trump) and feeling it has moved too far right, so they're trying to distinguish themselves from the populist right that seems to be everywhere.\n\nI fear that if this continues, the \"left-libertarians\" will move over to the Democratic party (about 6% or ~5 million registered Democrats are libertarians already vs. 12% or ~10 million libertarian Republicans) and maybe some of the moderates Republicans as well.\n\nHowever, the Democratic party seems to be gearing up to get back to it's protectionist roots with their \"better deal\" nonsense, so I don't know, we might be seeing a pendulum effect that will keep many Republicans from jumping to the Democrats.\n\nI don't see myself being a full on Democrat supporter, unless the majority turned into Third-Wayers or something, and I hold out hope for more Bill Weld-like, moderate, liberal, whatever, Republicans to turn it around.\n\nidk, just my thoughts, agreed with a lot of what you wrote.",
            "created_utc": 1511380496,
            "id": "dq7cwoa",
            "link_id": "t3_7er7p9",
            "parent_id": "t3_7er7p9",
            "permalink": "/r/tuesday/comments/7er7p9/to_the_republicans_and_independents_here_why_not/dq7cwoa/",
            "retrieved_on": 1511380498,
            "score": 1,
            "stickied": false,
            "subreddit": "tuesday",
            "subreddit_id": "t5_2r8s0"
        }
    ]
};
